name: flutter_service_locator
description: A starting point for Dart libraries or applications.
version: 1.0.0
author: Guy Peled <guypeled76@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  service_locator:
    git: https://github.com/guypeled76/service_locator

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
